# Generated by Django 4.2 on 2025-01-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('released', models.DateField(blank=True, null=True)),
                ('background_image', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, default=0, null=True)),
                ('metacritic_score', models.IntegerField(blank=True, default=0, null=True)),
                ('playtime', models.IntegerField(blank=True, default=0, null=True)),
                ('platforms', models.TextField(blank=True, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('stores', models.CharField(blank=True, max_length=255, null=True)),
                ('esrb_rating', models.CharField(blank=True, max_length=255, null=True)),
                ('screenshots', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
