# Generated by Django 4.2 on 2025-03-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
