# Generated by Django 4.2 on 2025-01-15 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_chatsession_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='message',
            new_name='messages',
        ),
    ]
