# Generated by Django 4.2 on 2025-01-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('released', models.DateField()),
                ('background_image', models.URLField()),
                ('rating', models.FloatField(default=0)),
                ('metacritic_score', models.IntegerField(default=0, null=True)),
                ('playtime', models.IntegerField(default=0)),
                ('platforms', models.JSONField()),
                ('genres', models.JSONField()),
                ('stores', models.CharField(max_length=255)),
                ('esrb_rating', models.CharField(max_length=255)),
                ('screenshots', models.JSONField()),
            ],
        ),
    ]
