# Generated by Django 4.2 on 2025-01-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_background_image_alter_game_esrb_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='screenshots',
            field=models.TextField(blank=True, null=True),
        ),
    ]
